name: MagicEffects
version: "1.1"
main: org.tahoma.magiceffects.MagicEffects
api-version: "1.16"
description: "Плагин для выбора и отображения магических эффектов."
Author: Tahoma34

commands:
  magiceffects:
    description: "Основная команда для MagicEffects"
    usage: "/magiceffects menu"
    aliases: [meff, meffects]
